twitter_api.config:
  type: config_object
  label: 'Credentials to authenticate with Twitter API'
  mapping:
    oauth_access_token:
          type: text
          label: 'Access Token'
    oauth_access_token_secret:
          type: text
          label: 'Access Token Secret'
    consumer_key:
          type: text
          label: 'Consumer key'
    consumer_secret:
          type: text
          label: 'Consumer secret'

instagram_api.config:
  type: config_object
  label: 'Credentials to authenticate with Instagram API'
  mapping:
    oauth_access_token:
          type: text
          label: 'Access Token'
    oauth_access_token_secret:
          type: text
          label: 'Access Token Secret'
    consumer_key:
          type: text
          label: 'Consumer key'
    consumer_secret:
          type: text
          label: 'Consumer secret'
